# Generated by Django 5.2.16 on 2026-08-26 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='ask_me',
            new_name='Ask_A_Question',
        ),
    ]
